### ISSUE TITLE
[BUG] When I try to make a "build_chrome" executable the pexe37 module crashes 

### ISSUE THREAD

**Issue by DjarDjar** [darkarp/malkit#3]
My python version is 3.7.0
Basically when I run `python malkit.py build_chromepass --email --address mygmail@gmail.com` , it makes the exe (which doesn't work) but it also adds a chromepass.log which says:

```
Traceback (most recent call last):
  File "importlib\resources.pyc", line 283, in open_resource
OSError: [Errno 0] Error: 'certifi\\cacert.pem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chromepass.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "_malkit\cookiesteal.pyc", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "requests\__init__.pyc", line 120, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "requests\utils.pyc", line 40, in <module>
  File "<boot hacks>", line 9, in override_where
  File "certifi\core.pyc", line 37, in where
  File "contextlib.pyc", line 112, in __enter__
  File "importlib\resources.pyc", line 201, in path
  File "importlib\resources.pyc", line 91, in open_binary
  File "importlib\resources.pyc", line 285, in open_resource
FileNotFoundError: certifi/cacert.pem

```

**Comment by AmbujKRSingh** [comment]
yup same for m

**Comment by darkarp** [comment]
The entire project will be updated, or should I say rewritten, soon. It will be better than ever :D
